# Generated by Django 2.2 on 2019-06-20 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='departure date')),
                ('arrival_time', models.DateField(verbose_name='arrival date')),
                ('number_of_seats', models.PositiveSmallIntegerField(default=0, help_text='Type the number of avaliable seats in this flight: ', validators=[django.core.validators.MaxValueValidator(5)])),
                ('ticket_price', models.PositiveIntegerField(default=0, help_text='Type the price for the ticket: ', validators=[django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name_plural': 'Flights',
                'ordering': ['departure_time', 'arrival_time'],
                'verbose_name': 'Flight',
            },
        ),
        migrations.CreateModel(
            name='Tourists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='First name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Choose the gender: ', max_length=1, verbose_name='Gender')),
                ('country', models.CharField(max_length=250, verbose_name='Country')),
                ('remarks', models.TextField(blank=True, help_text='Type remarks: ', verbose_name='Remarks')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('list_of_flights', models.ManyToManyField(to='spacecruise.Flights')),
            ],
            options={
                'verbose_name_plural': 'Flights',
                'ordering': ['first_name', 'last_name', 'date_of_birth'],
                'verbose_name': 'Flight',
            },
        ),
        migrations.AddField(
            model_name='flights',
            name='list_of_tourists',
            field=models.ManyToManyField(to='spacecruise.Tourists'),
        ),
    ]
