# Generated by Django 2.2 on 2019-06-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacecruise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourists',
            options={'ordering': ['first_name', 'last_name', 'date_of_birth'], 'verbose_name': 'Tourist', 'verbose_name_plural': 'Tourists'},
        ),
        migrations.AlterField(
            model_name='flights',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='arrival date'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='list_of_tourists',
            field=models.ManyToManyField(blank=True, related_name='tourists', to='spacecruise.Tourists'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='number_of_seats',
            field=models.PositiveSmallIntegerField(default=0, help_text='Type the number of avaliable seats in this flight.'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='ticket_price',
            field=models.PositiveIntegerField(default=0, help_text='Type the price for the ticket.'),
        ),
    ]
